// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditReport struct {
	ID                  pgtype.UUID
	SessionID           pgtype.UUID
	FileName            string
	Status              string
	FailureReason       pgtype.Text
	TotalMonthlySpend   pgtype.Numeric
	ProjectedAnnualCost pgtype.Numeric
	PriceSpikeCount     int32
	CreatedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
}

type DemoSession struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type MerchantRegistry struct {
	ID                pgtype.UUID
	NormalizedName    string
	DisplayName       string
	Category          pgtype.Text
	CancellationUrl   pgtype.Text
	CancellationSteps []byte
	FrictionLevel     string
	IsVerified        bool
	UpdatedAt         pgtype.Timestamptz
}

type Subscription struct {
	ID                 pgtype.UUID
	AuditReportID      pgtype.UUID
	MerchantRegistryID pgtype.UUID
	RawMerchantName    string
	NormalizedName     string
	BillingFrequency   string
	CurrentAmount      pgtype.Numeric
	PreviousAmount     pgtype.Numeric
	IsPriceCreep       bool
	ConfidenceScore    pgtype.Numeric
	UserActionStatus   string
	FirstDetectedDate  pgtype.Date
	LastDetectedDate   pgtype.Date
}
