// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const checkDB = `-- name: CheckDB :one
SELECT 1::int AS ok
`

func (q *Queries) CheckDB(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, checkDB)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
