// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: auditor/v1/auditor.proto

package auditorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Auditor_AuditStatement_FullMethodName = "/auditor.v1.Auditor/AuditStatement"
)

// AuditorClient is the client API for Auditor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Auditor processes redacted bank statements and streams audit progress events.
type AuditorClient interface {
	AuditStatement(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditEvent], error)
}

type auditorClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditorClient(cc grpc.ClientConnInterface) AuditorClient {
	return &auditorClient{cc}
}

func (c *auditorClient) AuditStatement(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Auditor_ServiceDesc.Streams[0], Auditor_AuditStatement_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AuditRequest, AuditEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Auditor_AuditStatementClient = grpc.ServerStreamingClient[AuditEvent]

// AuditorServer is the server API for Auditor service.
// All implementations must embed UnimplementedAuditorServer
// for forward compatibility.
//
// Auditor processes redacted bank statements and streams audit progress events.
type AuditorServer interface {
	AuditStatement(*AuditRequest, grpc.ServerStreamingServer[AuditEvent]) error
	mustEmbedUnimplementedAuditorServer()
}

// UnimplementedAuditorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditorServer struct{}

func (UnimplementedAuditorServer) AuditStatement(*AuditRequest, grpc.ServerStreamingServer[AuditEvent]) error {
	return status.Errorf(codes.Unimplemented, "method AuditStatement not implemented")
}
func (UnimplementedAuditorServer) mustEmbedUnimplementedAuditorServer() {}
func (UnimplementedAuditorServer) testEmbeddedByValue()                 {}

// UnsafeAuditorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditorServer will
// result in compilation errors.
type UnsafeAuditorServer interface {
	mustEmbedUnimplementedAuditorServer()
}

func RegisterAuditorServer(s grpc.ServiceRegistrar, srv AuditorServer) {
	// If the following call pancis, it indicates UnimplementedAuditorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Auditor_ServiceDesc, srv)
}

func _Auditor_AuditStatement_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AuditRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuditorServer).AuditStatement(m, &grpc.GenericServerStream[AuditRequest, AuditEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Auditor_AuditStatementServer = grpc.ServerStreamingServer[AuditEvent]

// Auditor_ServiceDesc is the grpc.ServiceDesc for Auditor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Auditor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auditor.v1.Auditor",
	HandlerType: (*AuditorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AuditStatement",
			Handler:       _Auditor_AuditStatement_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "auditor/v1/auditor.proto",
}
